#define UIP_CONF_ND6_SEND_NS 1
#define ENERGEST_CONF_ON 1
#define ENERGEST_CONF_ADDITIONS ENERGEST_TYPE_TEMP,ENERGEST_TYPE_WIND

#ifdef BUFSIZE
#define UIP_CONF_BUFFER_SIZE BUFSIZE
#endif /* BUFSIZE */
